### PR TITLE
Update autoware to 2024.3 version

### PR DESCRIPTION
**Pull request by habby1012**
**Issue to be solved:**
1. After launching autoware,  it has to take about two minutes for 'auto' to work. 
'Common_ground_filter' node in the perception module seems to be the root cause, as it is not loaded in the first two minutes. 'Common_ground_filter' node -> ... -> '/perception/obstacle_segmentation/pointcloud' topic -> 'behavior_velocity_planner' node in the planning module -> planning function doesn't work well -> can not 'auto'.

2. Check the difference between centerpoint and centerpoint_tiny

**Things that have be done:**
Update autoware to 2024.3 version. You can check the details in commit messages.

### CODE REVIEW

**Comment by YangXianqi** [comment]
These days, the period of compiling will fail

**Comment by habby1012** [comment]
Hello @YangXianqi!
In which part you encounter the compiling error?

**Comment by YangXianqi** [comment]
> Hello @YangXianqi! In which part you encounter the compiling error?

Hy @habby1012 !
1. During compiling the autoware, the commit ids of core/autoware_internal_msgs and core/autoware_adapi_msgs seem to not be valid. 

2. During compiling the bridge, `make prepare_bridge` will report “configure: error: cannot compute suffix of object files:  compile"

**Comment by habby1012** [comment]
Hello @YangXianqi !

1. Are you using the "update autoware" branch or other branch?
2. Did you follow [this page](https://autoware-carla-launch.readthedocs.io/en/latest/build.htmlhttps://autoware-carla-launch.readthedocs.io/en/latest/build.html) to build the environment?
 
You can provide more information about how you proceeded, so i can try to reproduce and help you find the problem. Thank you!

**Comment by YangXianqi** [comment]
> Hello @YangXianqi !
> 
> 1. Are you using the "update autoware" branch or other branch?
> 2. Did you follow [this page](https://autoware-carla-launch.readthedocs.io/en/latest/build.htmlhttps://autoware-carla-launch.readthedocs.io/en/latest/build.html) to build the environment?
> 
> You can provide more information about how you proceeded, so i can try to reproduce and help you find the problem. Thank you!

Thanks @habby1012 ！
1. I am using the "update autoware" branch" to compoile the project

2. During compiling the bridge， when `make prepare_bridge` is used, the error will occur:
image

3. During compiling the autoware, the commid id seems to be invalid: 
image

**Comment by habby1012** [comment]
Hi @YangXianqi !

The log of compiling the Autoware you show seems like the Autoware version is not compatible.
Since i have [updated the Autoware version to 2024.6](https://github.com/evshary/autoware_carla_launch/commit/fe0a8d4f256494ebb769e93cb4da14e76c297b0d) these days, i am not sure whether this is the cause or not. Maybe you can check this first.

**Comment by YangXianqi** [comment]
> Hi @YangXianqi !
> 
> The log of compiling the Autoware you show seems like the Autoware version is not compatible. Since i have [updated the Autoware version to 2024.6](https://github.com/evshary/autoware_carla_launch/commit/fe0a8d4f256494ebb769e93cb4da14e76c297b0d) these days, i am not sure whether this is the cause or not. Maybe you can check this first.

Thanks @habby1012 ！
I have checked the repo of the projects with mistakes, the corresponding commit id, such as ed9bd6535347214a8139df32f6b321265067690e in autoware_adapi_msgs and autoware_internal_msgs seems to be invalid. On the other hand, have you met the occured error in compiling the bridge?

**Comment by habby1012** [comment]
Hi @YangXianqi !

About the compiling problem of Autoware, are you using the 2024.6 Autoware docker image, or is your image still the older version such as 2024.3?
Regarding the occured error in compiling the bridge, i didn't meet such error.

I think you can try using 'docker images' command and check if you are using the right docker image first. If your docker image is still the old version, you should use 'git pull' to update the autoware_carla_launch repo and try to build it again.
Hope this is useful to you!

**Comment by YangXianqi** [comment]
Thanke @habby1012 ！

I have rebuilt the image based on ghcr.io/autowarefoundation/autoware:20240603-prebuilt-cuda-amd64. 

image

But when i use the command `make prepare_bridge`, the error occured again:
image

In addition, the autoware image i used is 2024.6.

**Comment by habby1012** [comment]
Hi @YangXianqi 
Sorry for the late reply. I'm off from the office for about ten days starting from today, but I will still try to help.

Can you show the content of the file /tmp/python-build* showed in the yellow error log for me? You can upload the file, and I will take a look.
I guess it may be something like the permission issue.

**Comment by YangXianqi** [comment]
> Hi @YangXianqi Sorry for the late reply. I'm off from the office for about ten days starting from today, but I will still try to help.
> 
> Can you show the content of the file /tmp/python-build* showed in the yellow error log for me? You can upload the file, and I will take a look. I guess it may be something like the permission issue.

Thanks a lot. I found the error is caused by permission. When i update the permission by `sudo chmod 777 /var/tmp/ccache`, the compilation is  successful. In addition, in order to compile the autoware successfully, the reference id of core/autoware_adapi_msgs in autoware.repos is updated to fe1ba2901fe019c7b023c6f2f17c6af7cb0551a4. But when i launch the autoware, there is the error:

image

Have u met the error? And can u help me to fix the problem.

**Comment by YangXianqi** [comment]
> Hi @YangXianqi Sorry for the late reply. I'm off from the office for about ten days starting from today, but I will still try to help.
> 
> Can you show the content of the file /tmp/python-build* showed in the yellow error log for me? You can upload the file, and I will take a look. I guess it may be something like the permission issue.

Thanks a lot! I have fixed this problem. It is caused by permission problem

**Comment by habby1012** [comment]
Hi @YangXianqi, Sorry for the late reply again!
Have you solved this issue? Did it happen when you try to build autoware?

**Comment by evshary** [comment]
Close the PR since it's replaced by https://github.com/evshary/autoware_carla_launch/pull/130

**Pull request closed without merging**
